const scrambleWords = [
  { word: "apple", hint: "A red or green fruit." },
  { word: "banana", hint: "A yellow fruit with a peel." },
  { word: "computer", hint: "An electronic device for processing data." },
  { word: "guitar", hint: "A musical instrument with strings." },
  { word: "ocean", hint: "A vast body of saltwater." },
  { word: "mountain", hint: "A large natural elevation of the earth's surface." },
  { word: "flower", hint: "A colorful bloom often found in gardens." },
  { word: "book", hint: "A written or printed work consisting of pages." },
  { word: "restaurant", hint: "A place where you can dine and enjoy food." },
  { word: "cat", hint: "A domesticated feline animal." },
  { word: "dog", hint: "A domesticated canine animal." },
  { word: "ball", hint: "A spherical object used in various sports and games." },
  { word: "tree", hint: "A tall plant with a trunk and branches." },
  { word: "house", hint: "A building where people live." },
  { word: "car", hint: "A motor vehicle with four wheels." },
  { word: "bicycle", hint: "A two-wheeled vehicle powered by pedals." },
  { word: "television", hint: "An electronic device for watching shows and movies." },
  { word: "shoes", hint: "Footwear worn to protect and comfort the feet." },
  { word: "phone", hint: "A communication device used for making calls." },
  { word: "music", hint: "A form of artistic expression through sound." },
  { word: "garden", hint: "An outdoor area with plants and flowers." },
  { word: "beach", hint: "A sandy shore by the sea." },
  { word: "school", hint: "A place for education and learning." },
  { word: "friend", hint: "A person you enjoy spending time with." },
  { word: "computer", hint: "An electronic device for processing data." },
  { word: "soccer", hint: "A popular sport played with a ball and goals." },
  { word: "coffee", hint: "A popular caffeinated beverage." },
  { word: "cake", hint: "A sweet dessert often served on special occasions." },
  { word: "umbrella", hint: "A device used to shield from rain or sun." },
  { word: "mirror", hint: "A reflective surface." },
  { word: "piano", hint: "A musical instrument with keys." },
  { word: "river", hint: "A natural flowing watercourse." },
  { word: "watch", hint: "A timekeeping device worn on the wrist." },
  { word: "hat", hint: "Headwear for sun protection or fashion." },
  { word: "globe", hint: "A spherical representation of the Earth." },
  { word: "moon", hint: "Earth's natural satellite." },
  { word: "star", hint: "A luminous celestial object in the night sky." },
  { word: "key", hint: "A small metal device used to unlock things." },
  { word: "camera", hint: "A device for capturing photographs." },
  { word: "chocolate", hint: "A sweet treat made from cacao." },
  { word: "fire", hint: "A burning process producing heat and light." },
  { word: "plane", hint: "A powered flying vehicle." },
  { word: "letter", hint: "A written or printed communication." },
  { word: "rainbow", hint: "A meteorological phenomenon with colorful arcs." },
  { word: "shark", hint: "A large predatory fish." },
  { word: "flower", hint: "A colorful bloom often found in gardens." },
  { word: "butterfly", hint: "An insect with colorful wings." },
  { word: "map", hint: "A representation of geographic information." },
  { word: "mountain", hint: "A large natural elevation of the earth's surface." },
  { word: "sun", hint: "The star at the center of our solar system." },
  { word: "moon", hint: "Earth's natural satellite." },
  { word: "cloud", hint: "A visible mass of water droplets in the sky." },
  { word: "candle", hint: "A source of light made of wax and a wick." },
  { word: "clock", hint: "A timekeeping device." },
  { word: "guitar", hint: "A musical instrument with strings." },
  { word: "sandwich", hint: "A food item consisting of fillings between bread slices." },
  { word: "painting", hint: "A work of art created with colors on a canvas." },
  { word: "sunglasses", hint: "Eyewear to protect the eyes from the sun." },
  { word: "bicycle", hint: "A two-wheeled vehicle powered by pedals." },
  { word: "puzzle", hint: "A game or toy that requires problem-solving." },
  { word: "beach", hint: "A sandy shore by the sea." },
  { word: "camera", hint: "A device for capturing photographs." },
  { word: "garden", hint: "An outdoor area with plants and flowers." },
  { word: "kite", hint: "A flying toy tethered to a string." },
  { word: "coin", hint: "A small, flat, typically round piece of metal used as currency." },
  { word: "ocean", hint: "A vast body of saltwater." },
  { word: "planet", hint: "A celestial body that orbits a star." },
  { word: "butterfly", hint: "An insect with colorful wings." },
  { word: "sandcastle", hint: "A sculpture made of sand at the beach." },
  { word: "jacket", hint: "Outerwear worn to keep warm." },
  { word: "wallet", hint: "A small, flat case for carrying personal items." },
  { word: "mirror", hint: "A reflective surface." },
  { word: "bracelet", hint: "Jewelry worn on the wrist." },
  { word: "spoon", hint: "A utensil for eating or stirring." },
  { word: "globe", hint: "A spherical representation of the Earth." },
  { word: "puzzle", hint: "A game or toy that requires problem-solving." },
  { word: "chocolate", hint: "A sweet treat made from cacao." },
  { word: "socks", hint: "Footwear that covers the ankles and feet." },
  { word: "swimming", hint: "An activity in water, often for recreation." },
  { word: "rainbow", hint: "A meteorological phenomenon with colorful arcs." },
  { word: "cake", hint: "A sweet dessert often served on special occasions." },
  { word: "ball", hint: "A spherical object used in various sports and games." },
  { word: "painting", hint: "A work of art created with colors on a canvas." },
  { word: "tiger", hint: "A large, striped big cat." },
  { word: "ship", hint: "A large boat for transportation on water." },
  { word: "train", hint: "A powered vehicle on a track for transportation." },
  { word: "kite", hint: "A flying toy tethered to a string." },
  { word: "cookie", hint: "A sweet baked treat." },
  { word: "robot", hint: "A machine capable of carrying out tasks autonomously." },
  { word: "diamond", hint: "A precious gemstone." },
  { word: "island", hint: "A piece of land surrounded by water." },
  { word: "shoe", hint: "Footwear worn to protect and comfort the feet." },
  { word: "bicycle", hint: "A two-wheeled vehicle powered by pedals." },
  { word: "keyboard", hint: "A device for typing on a computer." },
  { word: "pizza", hint: "A popular Italian dish with various toppings." },
  { word: "dragon", hint: "A mythical, fire-breathing creature." },
  { word: "star", hint: "A luminous celestial object in the night sky." },
  { word: "flower", hint: "A colorful bloom often found in gardens." },
  { word: "moon", hint: "Earth's natural satellite." },
  { word: "cloud", hint: "A visible mass of water droplets in the sky." },
  { word: "candle", hint: "A source of light made of wax and a wick." },
  { word: "clock", hint: "A timekeeping device." },
  { word: "guitar", hint: "A musical instrument with strings." },
  { word: "sandwich", hint: "A food item consisting of fillings between bread slices." },
  { word: "painting", hint: "A work of art created with colors on a canvas." },
  { word: "sunglasses", hint: "Eyewear to protect the eyes from the sun." },
  { word: "bicycle", hint: "A two-wheeled vehicle powered by pedals." },
  { word: "puzzle", hint: "A game or toy that requires problem-solving." },
  { word: "beach", hint: "A sandy shore by the sea." },
  { word: "camera", hint: "A device for capturing photographs." },
  { word: "garden", hint: "An outdoor area with plants and flowers." },
  { word: "kite", hint: "A flying toy tethered to a string." },
  { word: "coin", hint: "A small, flat, typically round piece of metal used as currency." },
  { word: "ocean", hint: "A vast body of saltwater." },
  { word: "planet", hint: "A celestial body that orbits a star." },
  { word: "butterfly", hint: "An insect with colorful wings." },
  { word: "sandcastle", hint: "A sculpture made of sand at the beach." },
  { word: "jacket", hint: "Outerwear worn to keep warm." },
  { word: "wallet", hint: "A small, flat case for carrying personal items." },
  { word: "mirror", hint: "A reflective surface." },
  { word: "bracelet", hint: "Jewelry worn on the wrist." },
  { word: "spoon", hint: "A utensil for eating or stirring." },
  { word: "globe", hint: "A spherical representation of the Earth." },
  { word: "puzzle", hint: "A game or toy that requires problem-solving." },
  { word: "chocolate", hint: "A sweet treat made from cacao." },
  { word: "socks", hint: "Footwear that covers the ankles and feet." },
  { word: "swimming", hint: "An activity in water, often for recreation." },
  { word: "rainbow", hint: "A meteorological phenomenon with colorful arcs." },
  { word: "cake", hint: "A sweet dessert often served on special occasions." },
  { word: "ball", hint: "A spherical object used in various sports and games." },
  { word: "painting", hint: "A work of art created with colors on a canvas." },
  { word: "tiger", hint: "A large, striped big cat." },
  { word: "ship", hint: "A large boat for transportation on water." },
  { word: "train", hint: "A powered vehicle on a track for transportation." },
  { word: "kite", hint: "A flying toy tethered to a string." },
  { word: "cookie", hint: "A sweet baked treat." },
  { word: "robot", hint: "A machine capable of carrying out tasks autonomously." },
  { word: "diamond", hint: "A precious gemstone." },
  { word: "island", hint: "A piece of land surrounded by water." },
  { word: "shoe", hint: "Footwear worn to protect and comfort the feet." },
];

